### ISSUE TITLE
Form renders but doesn't function

### ISSUE THREAD

**Issue by dlr1251** [sebkln/form_examples#2]
Hello, 

thank you for sharing this valuable piece of code.

I have tried to install it in my typo3 v. 9.5. using a sitepackage of typo3 8.7 I registered the YAML module configuration in the ext_localconf.php and the frontend config pluging tx in setup.typoscript.

The form renders correctly but it doesn't do anything when I click on next. How can I debug it?

**Comment by dlr1251** [comment]
I finally found what stopped the application to function: The "next button contained a generic css class name called "next" which stopped the javascript event to trigger since it was being called from another part of my app. Sorry for the inconvenience.

**Comment by sebkln** [comment]
Glad you already found the cause!
