### ISSUE TITLE
Request for extending the examples

### ISSUE THREAD

**Issue by wini2** [sebkln/form_examples#3]
Hello,

very helpfull examples, thanks a lot. 

As an expert for TYPO3-form-framework you may help me with two beginner-problems/questions I'm dealing with.

Is it possible to show up staticTexts on summary pages and e-mails? 
Is it possible to alter the output of checkboxes on summary-pages and e-mails form - or 1 to no or yes?

Maybe you could describe a solution or add to your examples.

Thanks for your help

**Comment by sebkln** [comment]
I answered [your question on StackOverflow](https://stackoverflow.com/questions/67923118/typo3-form-framework-e-mail-finisher-with-statictext/67947228).

StackOverflow or [TYPO3 Slack](https://typo3.org/community/meet/chat-slack) are the right places to ask these kind of questions, as there are plenty of kind TYPO3 people who can help you. Please don't use GitHub issues for general support. Thanks!
